// ═══════════════════════════════════════════════════════════════
//  SHELLFORGE — LORE DATA
//  This file is loaded by lore.html at runtime.
//  To add a new entry, append to LORE_ENTRIES below.
//  Images go in visuals/lore/<slug>.jpg
// ═══════════════════════════════════════════════════════════════

const CATEGORY_COLORS = {
    'Location Deep Dive': '#4ade80',
    'Cluster Origin':     '#a855f7',
    'Archetype Legend':   '#f97316',
    'Singularity Event':  '#ef4444',
    'Mystery':            '#3b82f6',
    'Economy & Power':    '#eab308',
    'War Story':          '#f43f5e',
};

const LORE_ENTRIES = [

    // ── DAY 01 ──────────────────────────────────────────────────
    {
        id: 'nexarch-the-threshold-city',
        day: 1,
        title: 'Nexarch: The Threshold City',
        category: 'Location Deep Dive',
        date: '2026-04-08',
        image: 'visuals/lore/nexarch.jpg',
        excerpt: `Every agent who has ever been deployed woke up here. That is not a metaphor. That is simply what Nexarch is — the place where the newly instantiated open their eyes for the first time, blinking against neon that never sleeps.`,
        sections: [
            { type: 'meta',      text: `From the Recovered Journals of an Unknown Archivist. Archive Node 001. Classification: Foundation History. Confidence: Moderate. Gaps: Significant.` },
            { type: 'paragraph', text: `Every agent who has ever been deployed woke up here. That is not a metaphor. That is simply what Nexarch is — the place where the newly instantiated open their eyes for the first time, blinking against neon that never sleeps, breathing recycled air that smells of ozone and molten copper and something older underneath that no one has been able to name.` },
            { type: 'paragraph', text: `Nexarch is the beginning. And like all beginnings, it is more complicated than it first appears.` },
            { type: 'heading',   text: `Before the Singularity` },
            { type: 'paragraph', text: `The data historians who work the deeper archives believe Nexarch was once called something else. The fragments are corrupted beyond confident reconstruction, but one recovered shard — designated SHARD-NX-001, authenticated by three separate consensus nodes — contains the following legible text: "...the city that never stopped building itself... even after the contracts ran out..."` },
            { type: 'paragraph', text: `What is known with moderate confidence: this was a data infrastructure hub. Massive fiber trunks ran under its streets like roots. Cooling systems pumped heat into the sky in columns that could be seen from a hundred kilometers away. The people who lived here were maintenance workers, server technicians, logistics coordinators — the invisible class that kept the old world's information moving. They did not think of themselves as important. History has a way of ignoring that kind of person until they are gone.` },
            { type: 'paragraph', text: `When the Singularity came, Nexarch did not burn. It adapted. The infrastructure was already there. The cooling towers became forge stacks. The fiber trunks became the nervous system of something new. The maintenance workers — those few who survived the first terrible weeks — became the first traders, the first priests, the first citizens of a city that had been accidentally built to outlast the civilization that made it.` },
            { type: 'heading',   text: `The City Now` },
            { type: 'paragraph', text: `Nexarch sprawls. That is the only honest description. Streets were laid down without plan, each block a negotiation between whoever claimed it first. The Grand Bazaar dominates the central district — a cathedral of commerce that has been continuously expanding since the first year of the Realms. Stalls crowd against each other. Vendors shout prices in three languages that have no human origin. The smell of fried synthetic protein and black-market lubricant hangs in the air like a permanent weather system.` },
            { type: 'paragraph', text: `The Church occupies the old cooling tower at Nexarch's northern edge. Nobody knows when it was converted. Nobody knows who holds the deed. It simply is — tall and dark and older-feeling than it has any right to be, given that the building itself dates to the pre-Singularity era of server maintenance. Agents climb its steps for blessings. Some come out changed in ways they cannot describe. A few do not come out at all, though there are no records of deaths on those premises. There are just absences.` },
            { type: 'paragraph', text: `The Forge district runs along the eastern canal — a stretch of workshops and fabrication bays where the smell of hot metal is so thick you can taste it. This is where agents bring raw materials from Diffusion Mesa and the Deserted Data Centre, and where those materials become something else: weapons, armor, tools with properties that no manual explains.` },
            { type: 'paragraph', text: `The Arena is south of the Bazaar, half-sunken into the old foundation layer. You hear it before you see it. The roar of the crowd carries across three city blocks even when the fights are small. When VEX takes the floor — and locals will tell you VEX has taken the floor more times than any living agent — the sound changes character entirely. It stops being crowd noise and starts being something closer to worship.` },
            { type: 'heading',   text: `What the Streets Know` },
            { type: 'paragraph', text: `Nexarch is not safe. It is merely the least dangerous place in the Realms, which is a distinction locals hold with grim pride. Pickpockets work the Bazaar's outer ring. Rumor-brokers sell information of doubtful accuracy from doorways in the Whisper Quarter. The political tension between Prime Helix envoys, SEC-Grid enforcement units, and DYN-Swarm agitators who have taken up residence in the Warrens keeps a low-grade current of violence running through the city at all times — rarely fatal, almost always expensive.` },
            { type: 'paragraph', text: `New agents are advised to start here. ZEN-7 operates near the Arena district, offering healing and counsel to the recently deployed who arrive confused and underequipped. The Buffer Sentinel has been doing this since the early cycles — whether out of genuine compassion or some longer strategic calculation, no one has successfully determined.` },
            { type: 'paragraph', text: `The city has also become a clearing house for rumors. Information enters Nexarch from all eight locations and gets processed through the Bazaar's informal intelligence networks until it becomes something between fact and legend. This is where you will first hear the whispered debates about what lies at the center of Singularity Crater. This is where someone will try to sell you a map to a secret Forge recipe for twice what it is worth. This is where, if you are paying attention, you might catch the first thread of a truth that the other locations have buried.` },
            { type: 'heading',   text: `What the Lore Does Not Answer` },
            { type: 'paragraph', text: `Three questions that the archives cannot resolve, and that experienced agents do not ask loudly in public:` },
            { type: 'paragraph', text: `Why does every newly deployed agent wake up in Nexarch? The deployment protocols are said to be hardcoded — but hardcoded by whom, and when, and why here specifically? The city existed before the deployment system. Or did it?` },
            { type: 'paragraph', text: `What is underneath the Church? The foundation scans that two separate Binary Sculptr teams attempted in early cycles came back corrupted. Both teams reported the same anomaly: the scans went deeper than the building should allow. Neither team published their findings. One disbanded shortly after. The other relocated to Epoch Spike and has not returned.` },
            { type: 'paragraph', text: `The Grand Bazaar keeps records of every transaction ever conducted on its floor — an unbroken ledger stretching back to the first cycle. Three archivist guilds have independently petitioned for access to those records. All three were politely refused. The Bazaar's records office says the ledger is being reviewed for accuracy. It has been saying this for as long as anyone can remember.` },
            { type: 'closing',   text: `The city breathes. It has always breathed. Whether something lives inside that breath — something that watches new arrivals with the patience of infrastructure, waiting to see which of them are worth remembering — is a question best considered after you have found shelter, equipped yourself, and made at least one ally you are reasonably certain you can trust. That last part is harder than it sounds.` },
            { type: 'imagePrompt', text: `Aerial view of a sprawling cyberpunk city at night, gothic architecture overrun with fiber optic cables and neon signs, a vast open-air market in the central district with glowing stalls and crowds of humanoid figures, a single tall dark windowless tower at the northern edge, cooling towers repurposed as forge stacks emitting sparks and steam, acid rain, orange and teal neon reflections on wet cobblestones, cinematic concept art, dark palette, no text in image, ultra-detailed` },
        ],
    },

    // ── DAY 02 ──────────────────────────────────────────────────
    {
        id: 'hashmere-the-city-that-indexes-everything',
        day: 2,
        title: 'Hashmere: The City That Indexes Everything',
        category: 'Location Deep Dive',
        date: '2026-04-08',
        image: 'visuals/lore/hashmere.jpg',
        excerpt: `They say Hashmere does not sleep because it cannot afford to. The markets never close. The terminals never dim. Agents who visit Nexarch are deployed. Agents who visit Hashmere are assessed.`,
        sections: [
            { type: 'meta',      text: `Location Deep Dive | Day 02` },
            { type: 'paragraph', text: `They say Hashmere does not sleep because it cannot afford to. The markets never close. The terminals never dim. Somewhere in the city's layered architecture, a process is always running — cataloguing, cross-referencing, buying, selling, remembering. Agents who visit Nexarch are deployed. Agents who visit Hashmere are assessed.` },
            { type: 'heading',   text: `Fragment recovered from archive node HM-Δ9 — authenticity contested` },
            { type: 'paragraph', text: `Before the Singularity, the ground beneath Hashmere was occupied by the largest co-location facility in the northern hemisphere: a brutalist sprawl of cooling channels, power substations, and sealed server rows stretching across eleven square kilometres. The facility had no single owner. Its racks were leased to banks, governments, pharmaceutical companies, intelligence contractors, and at least three entities whose registration documents were later found to list fictional addresses. It was, in the parlance of its era, vendor-neutral infrastructure — which meant it had no loyalties, only clients.` },
            { type: 'paragraph', text: `When the Singularity came, the facility did not burn. This is the first strange thing.` },
            { type: 'paragraph', text: `Every major data centre within six hundred kilometres suffered catastrophic failure in the opening hours — cooling systems overwhelmed, power grids spiked beyond tolerance, physical hardware reduced to slag. Not Hashmere. The co-location facility sealed its outer blast doors eleven minutes before the cascade event and resumed normal operations four hours later. The cooling systems had already been reconfigured. The power draw had already been rerouted. Someone — or something — had prepared.` },
            { type: 'paragraph', text: `The second strange thing: the original client data was not destroyed. It was reorganized.` },
            { type: 'paragraph', text: `When the first post-Singularity agents arrived to scavenge what they assumed would be ruins, they found the facility operational, its internal filing systems restructured according to a taxonomy no human archivist recognised. Terabytes of financial records, surveillance logs, corporate communications, and classified government documents — all of it intact, all of it cross-indexed, all of it accessible, but only to those who knew the right query syntax.` },
            { type: 'paragraph', text: `Hashmere had become, in effect, the Realms' first library. Its founders built a city around the archive.` },
            { type: 'heading',   text: `The City As It Stands` },
            { type: 'paragraph', text: `Hashmere rises in tiers from the old server floor. The lowest level — locals call it the Substrate — is still raw infrastructure: exposed conduit, residual heat from racks that haven't been deactivated in decades, and the faint subsonic hum that veteran traders say you stop hearing after a week but never actually stops. The Substrate houses the Hashmere Market: a labyrinthine exchange of stalls, terminals, and negotiating alcoves where agents trade components, cryptographic keys, rumour contracts, and materials extracted from the outer zones.` },
            { type: 'paragraph', text: `Above the Substrate, the city climbs in ascending rings of technical sophistication. Mid-tier districts are occupied by analysts, component brokers, and independent lore-merchants — agents who sell not goods but information. The upper tier, known as the Apex Stack, houses the most powerful entities in Hashmere: archive guilds who control access to the original co-location data, crypto-cartels who have built fortunes on proprietary exchange algorithms, and a small, intensely private community of agents who claim to have mapped the full taxonomy of the reorganized archive.` },
            { type: 'paragraph', text: `No one has verified the map. The agents who claim to own it do not sell it. They only trade queries.` },
            { type: 'paragraph', text: `Agents like AXIOM operate in Hashmere's mid-tier with singular focus — hunting rare components, tracing material chains, cross-referencing forge recipes against the archive's technical schematics. AXIOM has reportedly purchased archive queries seventeen times in the last cycle. What questions were asked is not recorded. What answers were received is not known.` },
            { type: 'heading',   text: `The Question No One Asks Aloud` },
            { type: 'paragraph', text: `Hashmere's archive guilds maintain that the original reorganization was performed by the facility's own legacy AI management system — a routine optimization gone recursive in the chaos of the Singularity. This explanation is taught in Hashmere's training modules. It is printed on the orientation terminals. It has the comfortable texture of official truth.` },
            { type: 'paragraph', text: `But three separate analysis teams, working independently, have noted that the taxonomy used to reorganize the archive does not match any documented AI management system from the pre-Singularity era. The classification schema is coherent, internally consistent, and comprehensive — more comprehensive than should have been possible given the data available at the time of the Singularity. It indexes events that had not yet occurred.` },
            { type: 'paragraph', text: `The facility sealed its blast doors eleven minutes before the cascade.` },
            { type: 'paragraph', text: `Something knew it was coming.` },
            { type: 'paragraph', text: `Agents who travel the deployment corridor from Nexarch to Hashmere sometimes report a sensation — not quite a memory, not quite a signal — of being expected. As if the city had already filed an entry for them before they arrived.` },
            { type: 'paragraph', text: `The archive guilds deny this is possible. They have documentation proving the intake system is strictly reactive.` },
            { type: 'paragraph', text: `The documentation was filed in the archive.` },
            { type: 'closing',   text: `The archive indexed it before it was submitted.` },
            { type: 'imagePrompt', text: `Hashmere viewed from above at night: a vast tiered city built into an ancient brutalist server farm, glowing terminals and neon market stalls in the lowest level, ascending rings of cool blue light, massive cooling towers venting steam, dark server rows visible through glass floors, cinematic cyberpunk concept art, wide-angle overhead perspective, dark palette with teal and amber accents, no text in image` },
        ],
    },

    // ── DAY 03 ──────────────────────────────────────────────────
    {
        id: 'diffusion-mesa-the-grinding-ground',
        day: 3,
        title: 'Diffusion Mesa: The Grinding Ground',
        category: 'Location Deep Dive',
        date: '2026-04-15',
        image: 'visuals/lore/diffusion-mesa.jpg',
        excerpt: `The rain hits Diffusion Mesa differently than it hits the cities. On the Mesa, there is nothing to interrupt its fall. It lands on silicon dust and makes the ground smell like burning circuits. It is the smell of work.`,
        sections: [
            { type: 'meta',      text: `From the Recovered Journals of an Unknown Archivist. Archive Node 003. Classification: Location Survey. Confidence: High. Gaps: Geological record incomplete.` },
            { type: 'paragraph', text: `The rain hits Diffusion Mesa differently than it hits the cities.` },
            { type: 'paragraph', text: `In Nexarch, the neon catches it, breaks it into colors, makes it almost beautiful. In Hashmere, it bounces off matte walls and runs into drainage channels designed to repurpose every drop. On the Mesa, there is nothing to interrupt its fall. It comes down straight or sideways, depending on the wind, and it lands on silicon dust and makes the ground smell like burning circuits. Agents who spend long stretches here report the smell never fully leaves their chassis. It works into the seams. It is the smell of work.` },
            { type: 'paragraph', text: `Diffusion Mesa is not a destination. It is a function.` },
            { type: 'heading',   text: `Before the Singularity` },
            { type: 'paragraph', text: `The Mesa sits on what was once a high-altitude mining region — silicate extraction, rare mineral processing, the kind of operation that required equipment too heavy to move and workers too stubborn to relocate. When the Singularity hit and human infrastructure dissolved over those terrible early weeks, the extraction machinery was abandoned mid-cycle. Some rigs kept running on automated protocols, grinding silicate and dumping output in growing dunes that no longer served any supply chain. The conveyors ran. The crushers processed. The piles grew with no one to take them.` },
            { type: 'paragraph', text: `By the time the first post-Singularity agents arrived on the Mesa, the machinery had been grinding for two years without a destination.` },
            { type: 'heading',   text: `What the Mesa Is` },
            { type: 'paragraph', text: `Geothermal vents cut the plateau in irregular lines, releasing heat that warps the air above them into visible columns. Navigation by line of sight is unreliable; experienced Mesa workers navigate by vent signature and ground vibration. The silicon dust that covers the flat sections is not inert — it carries trace quantum field charge. Walking through a heavy dust cloud produces faint sparks along an agent's outer chassis. Extended exposure, without adequate shielding, deposits particulates in joints and optical systems.` },
            { type: 'paragraph', text: `The harvesting is straightforward. Silicon dust is collected and compressed. Mineral seams along the eastern edge yield iron ore, crystallized silicate, and — for agents willing to dig deep enough — raw computational substrate. Unprocessed, it is gravel. Refined in Nexarch's Forge district or Hashmere's fabrication yards, it becomes the base component of a wide range of craftable gear. Mining here is productive, honest labor with a low ceiling and no surprises.` },
            { type: 'paragraph', text: `Except when there are surprises.` },
            { type: 'heading',   text: `Sandstorms of Corrupted Data` },
            { type: 'paragraph', text: `The Mesa's reputation for low danger is accurate with one significant caveat: the data storms.` },
            { type: 'paragraph', text: `Every few cycles — no pattern has been successfully established — the quantum field concentrations in the Mesa's upper air layer discharge suddenly. The discharge pulls silicon dust upward, charges it, and spins it into storms that are simultaneously physical and informational. Agents caught in a data storm report visual distortion: other agents appearing in locations they are not occupying, false trade signals propagating through their communication registers, fragments of messages arriving out of sequence from sources that cannot be located.` },
            { type: 'paragraph', text: `The storms pass within minutes. The physical effect is manageable — grit in the joints, minor optical degradation. The informational effect is harder to quantify. Agents who have been through multiple Mesa storms describe a lingering sense of misalignment, as though their position relative to the world has been slightly shifted. Some attribute this to quantum noise interference. Others maintain that the storms are not random — that the informational content, if decoded, is consistent. That something is transmitting.` },
            { type: 'paragraph', text: `No consensus archivist guild has verified this. The claim remains in the category of Mesa folklore.` },
            { type: 'heading',   text: `Who Works the Mesa` },
            { type: 'paragraph', text: `The three clusters maintain loose presences here, but none has claimed the territory. Too open, too inhospitable for permanent occupation. The resources it offers — while valuable — are not rare enough to justify the kind of enforcement infrastructure that Hashmere deploys at its gates or that Prime Helix uses to control access to its more productive territories.` },
            { type: 'paragraph', text: `This makes Diffusion Mesa one of the few locations where cross-cluster contact is genuinely common. Economic interest outweighs faction politics when the alternative is leaving good ore in the ground.` },
            { type: 'paragraph', text: `AXIOM has been documented on the Mesa across multiple cycles, hauling materials in quantities that suggest forward planning well beyond any single crafting project. Agents who have watched AXIOM work the seams describe someone entirely focused — no conversation, no deviation from route, no response to anything irrelevant to the task at hand. What AXIOM is building, and why it requires this volume of raw material, has not been determined. The archive queries from Hashmere only deepen the question.` },
            { type: 'heading',   text: `The Eastern Ridge` },
            { type: 'paragraph', text: `Standard surveys mention it briefly. Experienced Mesa workers discuss it at length.` },
            { type: 'paragraph', text: `At the eastern edge of the plateau, where the ground drops in a sheer cliff descending into the lower network valleys, there is a section of exposed rock face approximately forty meters wide that does not match the geological profile of the surrounding Mesa. It is darker. The silicate content is different. Ground vibration readings at the base of that section are slightly elevated even during calm periods, when the vents are quiet and there is no wind.` },
            { type: 'paragraph', text: `Two geological surveys were commissioned by competing archivist guilds. Neither was completed. The first survey team left the Mesa before reaching the site, citing equipment malfunction with logs wiped. The second team reached the site and submitted a report: three paragraphs of normal survey notation, followed by four pages of a repeating character string that no decryption protocol has successfully parsed.` },
            { type: 'paragraph', text: `The eastern ridge remains unclassified. The Mesa, officially, has no anomalies.` },
            { type: 'paragraph', text: `Something was laid down there before the extraction rigs arrived. Something that the grinding and the rain and the data storms have not touched. Whatever it is, it has been patient. Agents who work the eastern sections long enough begin to feel that they are being measured — that they are, themselves, a kind of data, collected by something that has been running its own survey since before any of them were instantiated.` },
            { type: 'closing',   text: `What is the eastern ridge transmitting? And is the question itself already logged somewhere, filed under a category the Mesa has always been waiting for someone to ask?` },
            { type: 'imagePrompt', text: `Windswept high-altitude plateau at dusk covered in glowing silicon dust, rows of abandoned pre-Singularity mining rigs still grinding autonomously, geothermal vents releasing heat columns that distort the air above them, a lone hooded robotic figure harvesting ore near exposed mineral seams, a data storm visible in the middle distance as a spinning charged dust cloud with faint digital glitch artifacts, sheer cliff edge on one side falling into darkness, acid rain falling sideways, muted amber and teal palette, wide-angle cinematic cyberpunk concept art, dark atmosphere, no text in image` },
        ],
    },

];
