export const STR = {
  title: "Netherveil",
  subtitle: "Medieval Cyberpunk City",
  cathedral: "Cathedral",
  arena: "Arena",
  watchtower: "Watchtower",
  market: "Market",
  church: "Church",
  foundry: "Foundry",
  tavern: "Tavern",
  explore: "Explore the city",
  discovered: "District Discovered",
  press_interact: "Press E / Tap to interact",
  lore_cathedral: "The Cathedral looms above the city, its ancient spires wrapped in pulsing circuit veins. Here the Techno-Priests maintain the city's core data nexus, merging prayer with protocol.",
  lore_arena: "The Arena — a colosseum of iron and neon where cyber-gladiators clash. The roar of the crowd mingles with the hum of overclocked servos.",
  lore_watchtower: "The Watchtower pierces the western fog. Its beacon — part flame, part hologram — scans the dark forest for threats both physical and digital.",
  lore_market: "The Market is the city's beating heart. Merchants hawk enchanted potions alongside black-market firmware. Every transaction leaves a trace on the grid.",
  lore_church: "The Church of the Old Code. Monks chant binary hymns beneath stained glass that shifts like a screensaver. The faithful debug their souls here.",
  lore_foundry: "The Foundry never sleeps. Massive gears grind ore into circuit-laced alloys, while smiths forge blades that can cut through both steel and firewalls.",
  lore_tavern: "The Tavern at the South Gate — first stop for every traveler. Mead flows freely, and the barkeep trades rumors encrypted in ale-stained ciphers.",
  controls_kb: "WASD / Arrows to move | E to interact",
  controls_touch: "Tap to move | Tap landmark to interact",
  minimap_label: "MAP"
};
