// AUTO-GENERATED by alchemy/build-catalog.js — do not edit by hand.
// Source: alchemy/items.csv + alchemy/recipes.csv
// Regenerate with: node alchemy/build-catalog.js

export const ALCHEMY_RECIPES = [
  {
    "item": "Plasma-Edged Servo Blade",
    "item_id": "plasma_edged_servo_blade",
    "category": "weapon",
    "station": "foundry",
    "hwsw": "hardware",
    "ing": [
      "tungsten_carbide_filings",
      "arc_welder_discharge",
      "industrial_flux_paste"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Railgun Forearm Mount",
    "item_id": "railgun_forearm_mount",
    "category": "weapon",
    "station": "foundry",
    "hwsw": "hardware",
    "ing": [
      "electron_flux_crystals",
      "titanium_mesh_strip",
      "magnetic_resonance_fluid"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Pneumatic Piston Fist",
    "item_id": "pneumatic_piston_fist",
    "category": "weapon",
    "station": "foundry",
    "hwsw": "hardware",
    "ing": [
      "salvaged_servo_joint",
      "hydraulic_compression_pulse",
      "industrial_flux_paste"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Tungsten Fragmentation Launcher",
    "item_id": "tungsten_fragmentation_launcher",
    "category": "weapon",
    "station": "foundry",
    "hwsw": "hardware",
    "ing": [
      "tungsten_carbide_filings",
      "plasma_server_slag",
      "hydraulic_compression_pulse"
    ],
    "rate": 60,
    "fail": "explosion_15"
  },
  {
    "item": "EMP Discharge Gauntlet",
    "item_id": "emp_discharge_gauntlet",
    "category": "weapon",
    "station": "foundry",
    "hwsw": "hardware",
    "ing": [
      "electron_flux_crystals",
      "coolant_gel_canister",
      "arc_welder_discharge"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Cryo-Bore Drill Lance",
    "item_id": "cryo_bore_drill_lance",
    "category": "weapon",
    "station": "foundry",
    "hwsw": "hardware",
    "ing": [
      "titanium_mesh_strip",
      "coolant_gel_canister",
      "magnetic_resonance_fluid"
    ],
    "rate": 60,
    "fail": "explosion_10"
  },
  {
    "item": "Nanobot Swarm Ejector",
    "item_id": "nanobot_swarm_ejector",
    "category": "weapon",
    "station": "foundry",
    "hwsw": "hardware",
    "ing": [
      "nanobot_swarm_gel",
      "salvaged_servo_joint",
      "magnetic_resonance_fluid"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Buffer Overflow Exploit",
    "item_id": "buffer_overflow_exploit",
    "category": "weapon",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "binary_code_shards",
      "hash_collision_powder",
      "memory_leak_elixir"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Neural Spike Virus",
    "item_id": "neural_spike_virus",
    "category": "weapon",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "gradient_descent_tears",
      "payload_injection_droplets",
      "backpropagation_serum"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "DDoS Swarm Protocol",
    "item_id": "ddos_swarm_protocol",
    "category": "weapon",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "nanobot_swarm_gel",
      "async_await_pulse",
      "null_pointer_solvent"
    ],
    "rate": 75,
    "fail": "slag"
  },
  {
    "item": "Zero-Day Payload",
    "item_id": "zero_day_payload",
    "category": "weapon",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "plasma_server_slag",
      "checksum_verify_acid",
      "jit_compiler_surge"
    ],
    "rate": 60,
    "fail": "explosion_10"
  },
  {
    "item": "Quantum Backdoor Exploit",
    "item_id": "quantum_backdoor_exploit",
    "category": "weapon",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "quantum_bit_residue",
      "api_endpoint_salts",
      "overclock_catalyst_spark"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "SQL Injection Payload",
    "item_id": "sql_injection_payload",
    "category": "weapon",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "base64_encoded_slime",
      "api_endpoint_salts",
      "cache_invalidation_brew"
    ],
    "rate": 60,
    "fail": "explosion_10"
  },
  {
    "item": "Ransomware Lockout Worm",
    "item_id": "ransomware_lockout_worm",
    "category": "weapon",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "fiber_optic_threads",
      "oauth_token_ichor",
      "null_pointer_solvent"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Tungsten Alloy Chassis Plate",
    "item_id": "tungsten_alloy_chassis_plate",
    "category": "armor",
    "station": "foundry",
    "hwsw": "hardware",
    "ing": [
      "tungsten_carbide_filings",
      "arc_welder_discharge",
      "magnetic_resonance_fluid"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Faraday Cage Neural Helm",
    "item_id": "faraday_cage_neural_helm",
    "category": "armor",
    "station": "foundry",
    "hwsw": "hardware",
    "ing": [
      "fiber_optic_threads",
      "electron_flux_crystals",
      "industrial_flux_paste"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Reactive Ceramic Plating",
    "item_id": "reactive_ceramic_plating",
    "category": "armor",
    "station": "foundry",
    "hwsw": "hardware",
    "ing": [
      "silicon_wafer_dust",
      "coolant_gel_canister",
      "hydraulic_compression_pulse"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Titanium Mesh Exoskeleton",
    "item_id": "titanium_mesh_exoskeleton",
    "category": "armor",
    "station": "foundry",
    "hwsw": "hardware",
    "ing": [
      "titanium_mesh_strip",
      "salvaged_servo_joint",
      "industrial_flux_paste"
    ],
    "rate": 60,
    "fail": "explosion_15"
  },
  {
    "item": "Cryo-Cooled Heat Sink Array",
    "item_id": "cryo_cooled_heat_sink_array",
    "category": "armor",
    "station": "foundry",
    "hwsw": "hardware",
    "ing": [
      "coolant_gel_canister",
      "electron_flux_crystals",
      "magnetic_resonance_fluid"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Salvaged Siege Chassis",
    "item_id": "salvaged_siege_chassis",
    "category": "armor",
    "station": "foundry",
    "hwsw": "hardware",
    "ing": [
      "nanobot_swarm_gel",
      "tungsten_carbide_filings",
      "hydraulic_compression_pulse"
    ],
    "rate": 60,
    "fail": "explosion_10"
  },
  {
    "item": "AES-256 Firewall Protocol",
    "item_id": "aes_256_firewall_protocol",
    "category": "armor",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "silicon_wafer_dust",
      "regex_pattern_filaments",
      "garbage_collector_tonic"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Homomorphic Encryption Cloak",
    "item_id": "homomorphic_encryption_cloak",
    "category": "armor",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "quantum_bit_residue",
      "attention_mechanism_dew",
      "virtual_machine_emulsion"
    ],
    "rate": 60,
    "fail": "explosion_10"
  },
  {
    "item": "Zero-Trust Authentication Layer",
    "item_id": "zero_trust_authentication_layer",
    "category": "armor",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "base64_encoded_slime",
      "oauth_token_ichor",
      "docker_image_distillate"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "TensorGuard Neural Shield",
    "item_id": "tensorguard_neural_shield",
    "category": "armor",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "epoch_cycle_blood",
      "tensorflow_igniter",
      "cache_invalidation_brew"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Sandbox Isolation Runtime",
    "item_id": "sandbox_isolation_runtime",
    "category": "armor",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "nanobot_swarm_gel",
      "payload_injection_droplets",
      "docker_image_distillate"
    ],
    "rate": 60,
    "fail": "explosion_10"
  },
  {
    "item": "Rate-Limiting Throttle Daemon",
    "item_id": "rate_limiting_throttle_daemon",
    "category": "armor",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "fiber_optic_threads",
      "hash_collision_powder",
      "async_await_pulse"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Coolant Flush Cartridge",
    "item_id": "coolant_flush_cartridge",
    "category": "consumable",
    "station": "foundry",
    "hwsw": "hardware",
    "ing": [
      "coolant_gel_canister",
      "overclock_catalyst_spark",
      "industrial_flux_paste"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Emergency Servo Lubricant",
    "item_id": "emergency_servo_lubricant",
    "category": "consumable",
    "station": "foundry",
    "hwsw": "hardware",
    "ing": [
      "salvaged_servo_joint",
      "gpu_render_flame",
      "magnetic_resonance_fluid"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Welding Patch Kit",
    "item_id": "welding_patch_kit",
    "category": "consumable",
    "station": "foundry",
    "hwsw": "hardware",
    "ing": [
      "silicon_wafer_dust",
      "arc_welder_discharge",
      "industrial_flux_paste"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Overclock Reactor Injector",
    "item_id": "overclock_reactor_injector",
    "category": "consumable",
    "station": "foundry",
    "hwsw": "hardware",
    "ing": [
      "electron_flux_crystals",
      "plasma_server_slag",
      "arc_welder_discharge"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "EMP Hardening Capsule",
    "item_id": "emp_hardening_capsule",
    "category": "consumable",
    "station": "foundry",
    "hwsw": "hardware",
    "ing": [
      "fiber_optic_threads",
      "titanium_mesh_strip",
      "magnetic_resonance_fluid"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Salvage Reclamation Drone",
    "item_id": "salvage_reclamation_drone",
    "category": "consumable",
    "station": "foundry",
    "hwsw": "hardware",
    "ing": [
      "nanobot_swarm_gel",
      "salvaged_servo_joint",
      "hydraulic_compression_pulse"
    ],
    "rate": 60,
    "fail": "explosion_15"
  },
  {
    "item": "Debug Rejuvenation Patch",
    "item_id": "debug_rejuvenation_patch",
    "category": "consumable",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "backpropagation_serum",
      "checksum_verify_acid",
      "garbage_collector_tonic"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Caffeine Gradient Booster",
    "item_id": "caffeine_gradient_booster",
    "category": "consumable",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "loss_function_sap",
      "cuda_kernel_ember",
      "memory_leak_elixir"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Cache Purge Tonic",
    "item_id": "cache_purge_tonic",
    "category": "consumable",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "gradient_descent_tears",
      "cache_invalidation_brew",
      "null_pointer_solvent"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Hot Patch Injection",
    "item_id": "hot_patch_injection",
    "category": "consumable",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "binary_code_shards",
      "api_endpoint_salts",
      "garbage_collector_tonic"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Context Window Expansion",
    "item_id": "context_window_expansion",
    "category": "consumable",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "token_embedding_vapor",
      "attention_mechanism_dew",
      "virtual_machine_emulsion"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Hyperparameter Tuning Shot",
    "item_id": "hyperparameter_tuning_shot",
    "category": "consumable",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "epoch_cycle_blood",
      "pytorch_flux_core",
      "halting_problem_paradox"
    ],
    "rate": 55,
    "fail": "explosion_15"
  },
  {
    "item": "Stable Diffusion Sequence",
    "item_id": "stable_diffusion_sequence",
    "category": "scroll",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "latent_space_fog",
      "token_embedding_vapor",
      "pytorch_flux_core"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "GAN Mirage Scroll",
    "item_id": "gan_mirage_scroll",
    "category": "scroll",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "latent_space_fog",
      "gpu_render_flame",
      "overclock_catalyst_spark"
    ],
    "rate": 60,
    "fail": "explosion_10"
  },
  {
    "item": "Transformer Attention Ritual",
    "item_id": "transformer_attention_ritual",
    "category": "scroll",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "attention_mechanism_dew",
      "epoch_cycle_blood",
      "tensorflow_igniter"
    ],
    "rate": 60,
    "fail": "explosion_10"
  },
  {
    "item": "Reinforcement Learning Prophecy",
    "item_id": "reinforcement_learning_prophecy",
    "category": "scroll",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "gradient_descent_tears",
      "loss_function_sap",
      "tensorflow_igniter"
    ],
    "rate": 60,
    "fail": "explosion_10"
  },
  {
    "item": "Bayesian Inference Divination",
    "item_id": "bayesian_inference_divination",
    "category": "scroll",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "attention_mechanism_dew",
      "checksum_verify_acid",
      "virtual_machine_emulsion"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Genetic Algorithm Evolution",
    "item_id": "genetic_algorithm_evolution",
    "category": "scroll",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "halting_problem_paradox",
      "nanobot_swarm_gel",
      "pytorch_flux_core"
    ],
    "rate": 55,
    "fail": "explosion_20"
  },
  {
    "item": "Prompt Engineering Curse",
    "item_id": "prompt_engineering_curse",
    "category": "scroll",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "token_embedding_vapor",
      "hash_collision_powder",
      "lambda_calculus_vapor"
    ],
    "rate": 55,
    "fail": "explosion_15"
  },
  {
    "item": "Recursive Function Spiral",
    "item_id": "recursive_function_spiral",
    "category": "scroll",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "loss_function_sap",
      "cuda_kernel_ember",
      "null_pointer_solvent"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Monte Carlo Simulation Rune",
    "item_id": "monte_carlo_simulation_rune",
    "category": "scroll",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "latent_space_fog",
      "regex_pattern_filaments",
      "kubernetes_pod_nectar"
    ],
    "rate": 60,
    "fail": "explosion_10"
  },
  {
    "item": "Gradient Vanishing Hex",
    "item_id": "gradient_vanishing_hex",
    "category": "scroll",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "gradient_descent_tears",
      "backpropagation_serum",
      "memory_leak_elixir"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "AlphaGo Neural Core",
    "item_id": "alphago_neural_core",
    "category": "artifact",
    "station": "foundry",
    "hwsw": "hardware",
    "ing": [
      "alpha_zero_primal_seed",
      "quantum_bit_residue",
      "magnetic_resonance_fluid"
    ],
    "rate": 45,
    "fail": "catastrophic"
  },
  {
    "item": "Quantum Annealer Processor",
    "item_id": "quantum_annealer_processor",
    "category": "artifact",
    "station": "foundry",
    "hwsw": "hardware",
    "ing": [
      "kolmogorov_complexity_crystal",
      "quantum_bit_residue",
      "cuda_kernel_ember"
    ],
    "rate": 40,
    "fail": "catastrophic"
  },
  {
    "item": "Von Neumann Self-Replicator",
    "item_id": "von_neumann_self_replicator",
    "category": "artifact",
    "station": "foundry",
    "hwsw": "hardware",
    "ing": [
      "von_neumann_probe_spores",
      "nanobot_swarm_gel",
      "hydraulic_compression_pulse"
    ],
    "rate": 45,
    "fail": "catastrophic"
  },
  {
    "item": "Satoshi Genesis Block Signet",
    "item_id": "satoshi_genesis_block_signet",
    "category": "artifact",
    "station": "foundry",
    "hwsw": "hardware",
    "ing": [
      "kolmogorov_complexity_crystal",
      "binary_code_shards",
      "industrial_flux_paste"
    ],
    "rate": 45,
    "fail": "catastrophic"
  },
  {
    "item": "GPT Oracle Crystal",
    "item_id": "gpt_oracle_crystal",
    "category": "artifact",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "token_embedding_vapor",
      "lambda_calculus_vapor",
      "turing_machine_essence"
    ],
    "rate": 40,
    "fail": "catastrophic"
  },
  {
    "item": "Blockchain Soulbound Key",
    "item_id": "blockchain_soulbound_key",
    "category": "artifact",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "binary_code_shards",
      "von_neumann_probe_spores",
      "kubernetes_pod_nectar"
    ],
    "rate": 45,
    "fail": "catastrophic"
  },
  {
    "item": "Federated Learning Nexus",
    "item_id": "federated_learning_nexus",
    "category": "artifact",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "gradient_descent_tears",
      "kubernetes_pod_nectar",
      "church_turing_thesis_core"
    ],
    "rate": 40,
    "fail": "catastrophic"
  },
  {
    "item": "Rust Borrow Checker Amulet",
    "item_id": "rust_borrow_checker_amulet",
    "category": "artifact",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "silicon_wafer_dust",
      "halting_problem_paradox",
      "garbage_collector_tonic"
    ],
    "rate": 40,
    "fail": "catastrophic"
  },
  {
    "item": "Hugging Face Model Repository",
    "item_id": "hugging_face_model_repository",
    "category": "artifact",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "token_embedding_vapor",
      "docker_image_distillate",
      "lambda_calculus_vapor"
    ],
    "rate": 45,
    "fail": "catastrophic"
  },
  {
    "item": "Dijkstra Shortest Path Compass",
    "item_id": "dijkstra_shortest_path_compass",
    "category": "artifact",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "church_turing_thesis_core",
      "attention_mechanism_dew",
      "async_await_pulse"
    ],
    "rate": 40,
    "fail": "catastrophic"
  },
  {
    "item": "Diagnostic Probe Array",
    "item_id": "diagnostic_probe_array",
    "category": "tool",
    "station": "foundry",
    "hwsw": "hardware",
    "ing": [
      "silicon_wafer_dust",
      "electron_flux_crystals",
      "industrial_flux_paste"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Soldering Gauntlet",
    "item_id": "soldering_gauntlet",
    "category": "tool",
    "station": "foundry",
    "hwsw": "hardware",
    "ing": [
      "tungsten_carbide_filings",
      "salvaged_servo_joint",
      "arc_welder_discharge"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Salvage Extraction Claw",
    "item_id": "salvage_extraction_claw",
    "category": "tool",
    "station": "foundry",
    "hwsw": "hardware",
    "ing": [
      "titanium_mesh_strip",
      "hydraulic_compression_pulse",
      "industrial_flux_paste"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Portable Foundry Anvil",
    "item_id": "portable_foundry_anvil",
    "category": "tool",
    "station": "foundry",
    "hwsw": "hardware",
    "ing": [
      "plasma_server_slag",
      "tungsten_carbide_filings",
      "arc_welder_discharge"
    ],
    "rate": 60,
    "fail": "explosion_15"
  },
  {
    "item": "Hydraulic Jack Lifter",
    "item_id": "hydraulic_jack_lifter",
    "category": "tool",
    "station": "foundry",
    "hwsw": "hardware",
    "ing": [
      "salvaged_servo_joint",
      "coolant_gel_canister",
      "hydraulic_compression_pulse"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Arc Welder Repair Rig",
    "item_id": "arc_welder_repair_rig",
    "category": "tool",
    "station": "foundry",
    "hwsw": "hardware",
    "ing": [
      "electron_flux_crystals",
      "tungsten_carbide_filings",
      "magnetic_resonance_fluid"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Git Rollback Module",
    "item_id": "git_rollback_module",
    "category": "tool",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "binary_code_shards",
      "fiber_optic_threads",
      "cache_invalidation_brew"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Docker Containerizer",
    "item_id": "docker_containerizer",
    "category": "tool",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "docker_image_distillate",
      "nanobot_swarm_gel",
      "virtual_machine_emulsion"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Kubernetes Orchestrator",
    "item_id": "kubernetes_orchestrator",
    "category": "tool",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "kubernetes_pod_nectar",
      "plasma_server_slag",
      "async_await_pulse"
    ],
    "rate": 60,
    "fail": "explosion_10"
  },
  {
    "item": "Wireshark Packet Sniffer",
    "item_id": "wireshark_packet_sniffer",
    "category": "tool",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "fiber_optic_threads",
      "api_endpoint_salts",
      "regex_pattern_filaments"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Nmap Reconnaissance Scanner",
    "item_id": "nmap_reconnaissance_scanner",
    "category": "tool",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "fiber_optic_threads",
      "regex_pattern_filaments",
      "virtual_machine_emulsion"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Vim Reality Editor",
    "item_id": "vim_reality_editor",
    "category": "tool",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "base64_encoded_slime",
      "hash_collision_powder",
      "null_pointer_solvent"
    ],
    "rate": 60,
    "fail": "explosion_15"
  },
  {
    "item": "Proximity Mine Cluster",
    "item_id": "proximity_mine_cluster",
    "category": "deployable",
    "station": "foundry",
    "hwsw": "hardware",
    "ing": [
      "electron_flux_crystals",
      "arc_welder_discharge",
      "industrial_flux_paste"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Razor Wire Entanglement Rig",
    "item_id": "razor_wire_entanglement_rig",
    "category": "deployable",
    "station": "foundry",
    "hwsw": "hardware",
    "ing": [
      "fiber_optic_threads",
      "tungsten_carbide_filings",
      "industrial_flux_paste"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Turret Drone Sentry",
    "item_id": "turret_drone_sentry",
    "category": "deployable",
    "station": "foundry",
    "hwsw": "hardware",
    "ing": [
      "titanium_mesh_strip",
      "salvaged_servo_joint",
      "arc_welder_discharge"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Magnetic Tether Trap",
    "item_id": "magnetic_tether_trap",
    "category": "deployable",
    "station": "foundry",
    "hwsw": "hardware",
    "ing": [
      "electron_flux_crystals",
      "titanium_mesh_strip",
      "hydraulic_compression_pulse"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "EMP Pulse Landmine",
    "item_id": "emp_pulse_landmine",
    "category": "deployable",
    "station": "foundry",
    "hwsw": "hardware",
    "ing": [
      "quantum_bit_residue",
      "plasma_server_slag",
      "magnetic_resonance_fluid"
    ],
    "rate": 60,
    "fail": "explosion_15"
  },
  {
    "item": "Honeypot Decoy Server",
    "item_id": "honeypot_decoy_server",
    "category": "deployable",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "binary_code_shards",
      "api_endpoint_salts",
      "docker_image_distillate"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Logic Bomb Tripwire",
    "item_id": "logic_bomb_tripwire",
    "category": "deployable",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "binary_code_shards",
      "payload_injection_droplets",
      "async_await_pulse"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Cryptojacker Leech Node",
    "item_id": "cryptojacker_leech_node",
    "category": "deployable",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "electron_flux_crystals",
      "gpu_render_flame",
      "memory_leak_elixir"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Rootkit Persistence Mine",
    "item_id": "rootkit_persistence_mine",
    "category": "deployable",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "base64_encoded_slime",
      "oauth_token_ichor",
      "garbage_collector_tonic"
    ],
    "rate": 70,
    "fail": "slag"
  },
  {
    "item": "Packet Storm Jammer",
    "item_id": "packet_storm_jammer",
    "category": "deployable",
    "station": "terminal",
    "hwsw": "software",
    "ing": [
      "quantum_bit_residue",
      "regex_pattern_filaments",
      "jit_compiler_surge"
    ],
    "rate": 60,
    "fail": "explosion_10"
  }
];
